### PR TITLE
issue/item metadata

### PR DESCRIPTION
**Pull request by olnrao**
Ability to associate metadata with data (or queue item).  I have submitted a feature request and these changes are in relation to that feature request.

Qup changes would be done in that qup github repository

### CODE REVIEW

**Comment by copiousfreetime** [comment]
Hi @olnrao, thanks for your pull request. Can you describe a scenario where you would use this type of feature? 

It seems to me that this is unnecessary. It does appear that kjess itself is utilizing this metadata, so it has no need to be aware of it. Client code that is utilzing kjess, and wants to send some additional data in the message should just encode it for itself.

In the call to `set`, the client code that is using kjess can create any object that it wants to send to queue. The object must respond to `to_s` and to be sent. So if there is additional data that the client software would need to use to process the message it is sending, it can create a serialization/deserialization model and pass the string representation to kjess, and then it can deserialize when it gets the data back. 

Since the metadata implementation you have here is not utilized by kjess itself, I would like a good use case description before adding this feature.

Does that make sense?

**Comment by olnrao** [comment]
Thanks for the quick reply, Jeremy.  

In short: this change is required for CollectiveIntellect collector module usage (which I think you are fully aware).

Can the 'functionality' be achived w/o touching kjess? - As you have pointed out: Yes

Why the change in KJess?  Just for efficiency.  Looks like my 'feature request' detailed write-up is not saved by GitHub.  KJess creates a protocol request as a 'string'. (with command, parameters separated by spaces, etc.).  This is a huge string of which 'data' is the 'big' part of it and plus a _copy_.  

Without this change, an extra 'data' copy (in-memory) is involved. With this change, I can avoid it.  

Where is the extra copy and how can I avoid with this change?
As you have seen in the diff, I will just have to concatenate both data and metadata with a _hard_to_occur_ separator.  This causes a copy internally to form a 'single' data parameter.  When playing with big data payloads, this comes as a cost. If I can delay this concatenation till protocol request preparation, I can avoid the cost.  Hence, the request.

Scenario?
We download data regularly and push to the queue.  We want to associate metadata such as: compressed, no. of messages, format (xml/json), etc. with every queue item pushed.  So that the dequeuer can act accordingly.  In case of a compressed item, the dequeuer decompresses and saves.  In case of dequeuer is batching based, it takes the no. of messages into account, etc.  

Eye-opener for me while investigating this:
String "<<" Vs. "+=" operartor - Former one causes 'append' semantics and later one causes 'copy' semantics.  I guess you know that Strings are mutable in Ruby.  So, 'append' semantics are less costly than 'copy' semantics.  Even in this case, if I follow string append it works.  But copy does trigger if the memory can not be extended underneath (esp. with huge payload).  I wish Ruby had a String(FixNum) to inform it approximate max buffer to allocate to help reduce this.  That would come as a huge benefit in case of protocol request preparation kind of scenarios.

Thanks,
Laxmi

**Comment by copiousfreetime** [comment]
@olnrao This is what I would do, and I'm assuming you are using KJess as the Qup adapter?
1. Create a new object for yourself, maybe call it `MyMessage`. Create this object with the data and the metadata you need for your situation.
2. Pass the instance of `MyMessage` to either `Qup::QueueAPI#produce` or `Qup::TopicAPI#publish` when you want to send that message to the queue or topic.
3. There must exist a `MyMessage#to_s` method so that you can encode your entire message into a String. `KJess::Client#set` ends up calling `#to_s` on the item passed to `#set`.
4. In your code on the receiving side, do something like:

``` ruby
# if you are using KJess directly
my_mesasge = MyMessage.from_string( kjess_client.get( queue_name ) )

# if you are using Qup
qup_msg = qup_consumer.consume
my_message = MyMessage.from_string( qup_msg.data )
```

Doing this allows you to encode the data in whatever manner you wish, all kjess needs to worry about is the `to_s` method on the object passed to it. 

On my side, I can definitely look at kjess and see if there is some efficiencies I can change up so that there is more efficient string manipulation when building its internal protocol strings.

Essentially, I would prefer that you manage your own specific serialization and deserialization. What I could do is add in a location in Qup and/or KJess for you to set the serialization/deserializer class for a queue/topic so it can be handled transparently by Qup/Kjess.

Thoughts?

**Comment by olnrao** [comment]
Thanks for bearing with me, Jeremy.  You hit the bulls eye.  That is what I am doing (StringIO is one such object in Ruby).  I felt that this is generic and can be pushed down as many people may not realize the intricacies with Ruby String semantics, plus the fact that KJess implements text protocol underneath.  

Anyway, I can drop this.  

But I still want to pursue using "<<" operator in as many places as possible than "+=", can I go and submit such a minor fix?

Thanks a lot for your patience,
Laxmi

**Comment by copiousfreetime** [comment]
@olnrao sure, no problem. I'd also like to explore the possibility of using StringIO instead. It may be even more efficient.

Can you put in here some average message lengths? I'd like to benchmark and see what will be the most effective.  I'm going to close this pull req, and we can have the experiments in string concatenation over at #22.

**Pull request closed without merging**
